version: "3.8"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - 8080

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - front

